apiVersion: apps/v1
kind: Deployment
metadata:
  name: pnrk-deploy
  labels: 
    env: prod
    app: winapp    
Spec:
  replicas: 5
  selector:
    matchLabels:
      env: prod    
  template:
    metadata:
      labels: 
        env: prod
    spec:
      containers:
      - image: C1
        name: dummyimage 
      nodeselector:
        app: winapp
  


